### ISSUE TITLE
[from:Eli Fisker] Next button for cloud lab projects

### ISSUE THREAD

**Issue by jeehyung** [eternagame/EteRNA-public#22]
Mainly I need to be able to click ”NEXT” after finishing a Player Project and then automaticly get sent somewhere I haven't been before.

**Comment by elifisker** [comment]
- I would like be able to open the project description from within the player project, I am playing. So I don't have to leave the project to read the mission I am on. Sometimes the mission info is needed along with the solving of the player project. 

For details on this , see my forum post: 

https://getsatisfaction.com/eternagame/topics/ideas_for_improving_the_player_projects

**Comment by elifisker** [comment]
- I would like links in the Project description to open in a seperate window, so I don't get taken away from the player project, just because I try to open outside links that got suggested, like eg. the SCOR database. 

For details, see my forum post:

https://getsatisfaction.com/eternagame/topics/ideas_for_improving_the_player_projects
