### ISSUE TITLE
TSV files have spaces instead of tabs and newlines

### ISSUE THREAD

**Issue by Omei** [eternagame/EteRNA-public#418]
This means they can't be used without a customized parser.

Example: http://eterna.cmu.edu/tsv/synthesis3413597.tsv

**Comment by jeejee85** [comment]
Hi @Omei

I assume you are viewing this on the browser. In browser, every tab, newline is interpreted as a whitespace. If you actually download the TSV, it displays with tabs correctly.

I'm closing this issue and creating a new issue where the browser will prompt download of the TSV files instead of showing it on the browser.

**Comment by Omei** [comment]
```
Yes, the real issue is getting useable data.On 11/20/2013 9:34 AM, jeejee85 wrote:

  Hi @Omei
  I assume you are viewing this on the browser. In browser, every
    tab, newline is interpreted as a whitespace. If you actually
    download the TSV, it displays with tabs correctly.
  I'm closing this issue and creating a new issue where the
    browser will prompt download of the TSV files instead of showing
    it on the browser.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by jeejee85** [comment]
Not it should download right away
